name = "mindful-balance-contact-form"
main = "src/index.js"
compatibility_date = "2025-03-25"
account_id = "1d881509c2679aa8b5023f278c2ea238"
tsconfig = "tsconfig.json"

send_email = [
    {name = "CONTACT_EMAIL", allowed_destination_addresses = ["cindy@mindfulbalanceadhdcoaching.com", "fcharris@gmail.com"]}
]

[observability]
enabled = true

[[routes]]
pattern = "mindfulbalanceadhdcoaching.com/api/contact"
zone_name = "mindfulbalanceadhdcoaching.com"

[[routes]]
pattern = "www.mindfulbalanceadhdcoaching.com/api/contact"
zone_name = "mindfulbalanceadhdcoaching.com"

# For development/testing on Pages subdomain, we'll use a separate worker deployment
# The main worker will handle the custom domain, and Pages will need a separate setup
